##############################################################################
# file explorer plugin
##############################################################################
##### file explorer #####

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
" Setting
nnoremap <silent><C-e> :NERDTreeToggle<CR>
let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsible = '▾'

" Show Hidden files and ignore files in NERDtree
let g:NERDTreeShowHidden=1
let g:NERDTreeIgnore=['\.DS_Store$', '\.git$']

'''

